/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#182034',
        'primary-container': '#2e354a',
        'on-primary': '#ffffff',
        'on-primary-container': '#979eb7',
        'on-primary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#3f465c',
        'primary-fixed': '#dae2fd',
        'primary-fixed-dim': '#bec6e0',
        secondary: '#515f74',
        'secondary-container': '#d5e3fd',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#57657b',
        'on-secondary-fixed': '#0d1c2f',
        'on-secondary-fixed-variant': '#3a485c',
        'secondary-fixed': '#d5e3fd',
        'secondary-fixed-dim': '#b9c7e0',
        tertiary: '#001f4b',
        'tertiary-container': '#003374',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#6a9dff',
        'on-tertiary-fixed': '#001a42',
        'on-tertiary-fixed-variant': '#004395',
        'tertiary-fixed': '#d8e2ff',
        'tertiary-fixed-dim': '#adc6ff',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f7f9fb',
        'on-background': '#191c1e',
        surface: '#f7f9fb',
        'on-surface': '#191c1e',
        'surface-variant': '#e0e3e5',
        'on-surface-variant': '#43474e',
        'surface-container': '#eceef0',
        'surface-container-low': '#f2f4f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-tint': '#565e74',
        outline: '#74777f',
        'outline-variant': '#c4c6cf',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#bec6e0',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
